version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - db
      - redis
    environment:
      RAILS_MAX_THREADS: 5

  db:
    image: mysql:5.7
    #restart: always
    #command: bash -c "bin/rails db:create db:migrate && bundle exec rails s -b 0.0.0.0"

    environment:
      #MYSQL_USER: "root"
      #MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: instabug_chat_app_development
    mem_limit: 4g

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  redis:
    image: redis:latest
    #command: redis-server
    ports:
      - "6379:6379"

